добавление и удаление комментариев
htmlacademy-ecmascript/199591-cinemaddict-16 pull request #13
Opened 2022-01-30 16:26 UTC by MitKat

2022-01-30 22:36 UTC, MitKat commented on src/presenter/film-list-presenter.js
> +  #filmsMostCommentedComponent = new FilmsListExtraView(TitleExtra.MOST_COMMENTED);
Добавила я два компонента....

2022-01-30 22:38 UTC, MitKat commented on src/presenter/film-list-presenter.js
> +            movieNew.then((movie6) => movie6.movie);
Так я и не разобралась, как получить либо кино, либо комментарии...пыталась их из Promise получить, но тоже не получилось. Хотя сами комментарии на сервер добавляются и при обновлении страницы там сохраняются.

2022-01-31 08:05 UTC, ElseeCCD commented on src/presenter/film-list-presenter.js
> +            movieNew.then((movie6) => movie6.movie);
Ну тут почти справилась. Надо только сделать функцию асинхронной:
```
const onCtrlEnterKeyDownHandler = async (evt) => {
...
```

Дальше тут ждём ответ от сервера:
```
const movieNew = await this.#apiService.addComment(filmItem, commentNew);
```

И дальше уже не надо никаких then, просто передаём в модель:
```
this.#moviesModel.updateFilm(UpdateType.MINOR, movieNew.movie);
```

Дальше обрати внимание, что у тебя происходит в модели с фильмом в методе updateFilm: он там отправляется на сервер опять. Нам этого не надо, это лишний запрос. Можно создать, например, дополнительный метод, который не будет отсылать лишних запросов:
```
updateFilmModel = (updateType, update) => {
    const index = this.#movies.findIndex((film) => film.id === update.id);

    if (index === -1) {
      throw new Error('Can\'t update unexisting film');
    }

    try {
      const updatedFilm = this.#adaptToClient(update);
      this.#movies = [
        ...this.#movies.slice(0, index),
        updatedFilm,
        ...this.#movies.slice(index + 1),
      ];
      this._notify(updateType, updatedFilm);
    } catch(err) {
      throw new Error('Can\'t update film');
    }
  }
```

Общие части для updateFilm и updateFilmModel опять же можно вынести в отдельные методы:
```
#findFilmIndex = (film) => {
  const index = this.#movies.findIndex((movie) => movie.id === film.id);

    if (index === -1) {
      throw new Error('Can\'t update unexisting film');
    }
    
    return index;
}

#updateMovies = (index, update, updateType) => {
  const updatedFilm = this.#adaptToClient(update);
  this.#movies = [
    ...this.#movies.slice(0, index),
    updatedFilm,
    ...this.#movies.slice(index + 1),
  ];
  this._notify(updateType, updatedFilm);
}
```

Тогда `updateFilm` и `updateFilmModel` станут чуть компактнее:
```
updateFilm = async (updateType, update) => {
    const index = this.#findFilmIndex(update);

    try {
      const response = await this.#apiService.updateMovie(update);
      this.#updateMovies(index, response, updateType);
    } catch(err) {
      throw new Error('Can\'t update film');
    }
  }

  updateFilmModel = (updateType, update) => {
    const index = this.#findFilmIndex(update);

    try {
      this.#updateMovies(index, update, updateType);
    } catch(err) {
      throw new Error('Can\'t update film model');
    }
  } 
```

2022-01-31 14:40 UTC, MitKat commented on src/view/comments-view.js
> +    this._data = CommentsPopupView.parseCommentsToData(this.#film);
Что то я закомитила с разными вариантами.
Вариант первый сделать через static parse.....тут я зависаю, когда делать parse в обратную сторону, хотя уже чуть лучше его начала понимать.....И надо делать Smart, чтобы был доступен метод updatData, его пытаюсь вызывать в film-list-presenter.
2. Вариант второй, просто создать флаги и передать в шаблон, но тут шаблон иногда ругался, и как обновлять не понимаю....

2022-01-31 14:41 UTC, MitKat commented on src/view/filter-view.js
> +      filter = evt.target.closest('a').name;
Тут наконец то нашла в интернете, как кнопки span у фильтров заработали, а то в ТЗ указано, а у меня ошибку выдавало, при клике на цифры.

2022-01-31 22:20 UTC, MitKat commented on src/presenter/film-list-presenter.js
> +        this.#popupComponent.shake(resetDelete);
Обратная связь на ошибки сети не совсем работает, по ТЗ все выполняется deleting снова становится delete, а форма отправки нового сообщения становится доступной, но сам shake не работает, нет никакой тряски, пробовала на разные компоненты его подключить, тоже тишина.

2022-02-01 12:26 UTC, ElseeCCD commented on markup/css/main.css
> +@keyframes shake {
В папке markup лежит разметка для проекта, html-странички, которые сделаны, чтобы вы могли к себе разметку забрать. Наша рабочая папка - это public, стили нужно добавить в `public/css/main.css`

2022-02-01 13:46 UTC, ElseeCCD requested changes

2022-02-01 13:46 UTC, ElseeCCD commented on src/presenter/film-list-presenter.js
> +          commentNew.emotion =  this.#popupNewCommentComponent._data.emotion;
Так, вот для этих 2-х полей давай геттеры создаадим в `new-comment-view.js`:
```
get commentText() {
  return this._data.text;
}

get emoji() {
  return this._data.emotion;
}
```

И тут уже этими геттерами будем пользоваться:
```
commentNew.text = this.#popupNewCommentComponent.commentText;
commentNew.emotion =  this.#popupNewCommentComponent.emoji;
 ```

2022-02-01 13:46 UTC, ElseeCCD commented on src/presenter/film-list-presenter.js
> +              const resetComment = () => this.#popupNewCommentComponent.updateData({isDisabled: false});
ну тут ты не сбрасываешь же комментарий, как раз наоборот, оставляешь поля формы нетронутыми ) Можно назвать как-нибудь unlockForm, например

2022-02-01 13:46 UTC, ElseeCCD commented on src/presenter/film-list-presenter.js
> +      }
Ну с удалением чуть намудрила ) Я понимаю, сама тебя запутала. Смотри, давай так, у нас в `CommentsPopupView` должны в _data храниться следующие поля (`comments-view.js`):
```
this._data = {
  isDeleting: false,
  deletingCommentId: null,
};
```

Теперь, по клику на кнопку delete, у нас что должно происходить: состояние должно меняться на `isDeleting` и записываться нужный айдишник комментария (это уже тут обновляем):
```
try {
  this.#savePopupPosition();
  this.#popupCommentsComponent.updateData({isDeleting: true, deletingCommentId: commentId});
  ...
```

А при ошибке это всё сбрасываем:
```
} catch(err) {
  const resetDelete = () => this.#popupCommentsComponent.updateData({isDeleting: false, deletingCommentId: null});
  ...
```

2022-02-01 13:46 UTC, ElseeCCD commented on src/view/comments-view.js
> +  #deletingCommentId = null;
вот это давай удалим )

2022-02-01 13:46 UTC, ElseeCCD commented on src/view/comments-view.js
> +      isDeleting: true,
так, тут по умолчанию isDeleting должно быть false, в начальном же состоянии мы ничего не удаляем. И давай добавим сюда `deletingCommentId`:
```
this._data = {
  isDeleting: false,
  deletingCommentId: null
}
```

2022-02-01 13:46 UTC, ElseeCCD commented on src/view/comments-view.js
> +    return createCommentsPopupTemplate(this.#comments, this._data.isDeleting, this.#deletingCommentId);
тут, соответсвенно, тоже обновляем:
```
return createCommentsPopupTemplate(this.#comments, this._data.isDeleting, this._data.deletingCommentId);
```

2022-02-01 13:46 UTC, ElseeCCD commented on src/view/comments-view.js
> +  restoreHandlers = () => { };
Нет, тут так не пойдёт, на кнопках delete нужно слушатели восстановить, иначе после неуспешной отправки будет всё ломаться по клику на Delete:
```
this.element.querySelectorAll('.film-details__comment-delete')
      .forEach((comment) => comment.addEventListener('click', (evt) => this.#commentDeleteClickHandler(evt, this.#film)));
```

Обрати внимание, что ровно это же написано в setDeleteClickHandler. Советую вынести в отдельную приватную функцию

2022-02-01 13:46 UTC, ElseeCCD commented on src/view/comments-view.js
> +    this.#deletingCommentId = commentId;
вот это тоже удалить

2022-02-01 17:12 UTC, ElseeCCD approved these changes

2022-02-01 17:13 UTC, merged