add mock file
htmlacademy-ecmascript/199591-cinemaddict-16 pull request #4
Opened 2021-11-29 12:26 UTC by MitKat

2021-11-29 12:29 UTC, MitKat commented on src/mock/film-card.js
> +function getRandomFloatNumber(number1, number2, floatPoint) {
Эту функцию писала на предыдущем интенсиве, ее и взяла.

2021-11-29 12:30 UTC, MitKat commented on src/view/film-card-view.js
> +  }
Вот тут вопрос, Сначала взялась пересчитывать сама минуты в часы, а теперь думаю не надо ли их пересчитывать с помощью dayjs?

2021-11-29 12:33 UTC, MitKat commented on src/view/film-card-view.js
> +  }
Вопрос. Я взялась пересчитывать сама минуты в часы, и зависла, а вдруг надо через dayjs? я просто в нем еще не разобралась.

2021-11-29 12:36 UTC, MitKat commented on src/view/film-card-view.js
>      <span class="film-card__comments">18 comments</span>
Вопрос с комментариями. Я правильно понимаю, мы заводим отдельный файл для структуры с комментариями, каким то образом связываем комментарии с карточкой фильма, и тогда в этой строке прописываем количество комментариев? 
Или сейчас для таких карточек достаточно высчитать рандомное число комментариев. А для попапа уже прописывать комментарии со структурой?

2021-11-29 12:41 UTC, MitKat commented on src/mock/film-card.js
> +    description: generateDescription(),
Вопрос.
У нас в ТЗ прописана структура карточки фильма, в целом названия я брала оттуда, но не повторяла ее полностью (имею ввиду объекты, массивы).
Я правильно понимаю, мы создаем один мок файл со всеми данными, в том числе и с теми которые будут в попапе. И просто, в карточки на главной странице мы не все данные будем брать?
Попап в этом задании надо генерировать?

2021-11-30 06:41 UTC, ElseeCCD commented on src/view/film-card-view.js
> +  }
Ну смотри, прям требования использовать dayjs нет, как и требования написать всё руками )  Тут выбирай сама: мне кажется, одинаково полезно будет и со сторонней библиотекой познакомиться, и руками поработать с датами (спойлер: это довольно сложно). На самом деле мне кажется, что с dayjs попроще будет, но поразбираться и подумать, как реализовать самой, конечно, интереснее ) Но нужно будет чуть сложнее реализовывать, чем у тебя сейчас, правильно? Что если 2 часа будет длительность, например? Или 3?

2021-11-30 06:58 UTC, ElseeCCD commented on src/view/film-card-view.js
>      <span class="film-card__comments">18 comments</span>
Все структуры можно посмотреть в ТЗ в разделе 1.9: https://up.htmlacademy.ru/ecmascript/16/project/cinemaddict#resource

Получается, если мы посмотрим структуру `Movie`, то увидим у неё массив `comments`, в котором хранится список айдишников комментариев. И есть эндпоинт `GET /comments/: film_id`, который будет присылать нам список комментариев для одного конкретного фильма (т.е. массив комментариев). У каждого комментария будет свой уникалььный id. Так и будем их связывать: берём айдишник из массива `comments` в структуре фильма и соотносим его с нужным комментарием.

Какой вариант решения я могу предложить в рамках создания моковых данных:
1) создать словарик, куда будем складывать комментарии для каждого конкретного фильма:
```
const commentsDictionary = {
  "тут_id_фильма": [тут_будут_комментарии_к фильму]
}
```
но на данном этапе это у нас пустой объект: `const commentsDictionary = {};`

2) при создании моковых данных для фильма:
- складываем его id в наш словарик и ассоциируем его с путым массивом: 
```
commentsDictionary[тут_id_фильма] = [];`
```
- Генерируем рандомные комментарии. Каждый комментарий добавляем в наш словарик:
```
commentsDictionary[тут_id_фильма].push(тут_комментарий_структуры_Comment);
```
И не забываем добавлять id комментария в массив comments самого фильма

2021-11-30 07:00 UTC, ElseeCCD commented on src/mock/film-card.js
> +    description: generateDescription(),
Да, структура данных будет одна и для карточки, и для попапа. Шаблон попапа заполнить нужно (пункт 4 ДЗ), но логику попапа пока реализовывать не нужно (открытие/закрытие и т.п.)

2021-11-30 07:38 UTC, ElseeCCD requested changes

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +  const titles = [
`const titles` можно вынести за пределы функции generateTitle, чтобы не пересоздавать массив на каждый вызов функции generateTitle. Это же как бы константа ) У нас даже критерий под это дело есть: https://up.htmlacademy.ru/ecmascript/16/criteries#d17

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +  const genres = [
тут то же самое, можно вынести за пределы

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +  const images = [
ну и тут )

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +  const descriptions = [
и здесь тоже )

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +const MAX_DISCRIPTION = 5;
Давай сразу стараться соблюдать критерии. У нас есть критерий Б14, которые требует. чтобы все константы шли сразу за импортами: https://up.htmlacademy.ru/ecmascript/16/criteries#b14

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +    const index = getRandomInteger(0, descriptions.length - 1);
при таком подходе предложения могут повторяться ) Могу предложить не через цикл делать, а, например, через "перемешивание" массива. При создании описания случайным образом перемешивать массив (функцию shuffleArray можно посмотреть, например, здесь: https://stackoverflow.com/a/12646864. Только нужно учитывать, что функция из примера меняет сам массив, поэтому его сначала желательно клонировать). А потом из этого массива брать первые n рандомных предложений. Как-то так:
```
const generateDescription =() => {
  const randomIndex = getRandomInteger(0, MAX_DISCRIPTION);
  const shuffledDescriptions = shuffleArray([...descriptions]);
  return shuffledDescriptions.slice(0, randomIndex).join(' ');
}
```

2021-11-30 07:38 UTC, ElseeCCD commented on src/mock/film-card.js
> +const MAX_YEAR = 2022;
тут всё то же самое, поднимаем константы наверх )

2021-12-02 18:29 UTC, MitKat commented on src/view/film-card-view.js
> +const duration = require('dayjs/plugin/duration');
Не знаю, что тут делать с этим плагином, нашла что его надо добавить, но теперь линт ругается

2021-12-03 06:42 UTC, ElseeCCD requested changes

2021-12-03 06:42 UTC, ElseeCCD commented on src/main.js
> +const cardsFilm = Array.from({length: FILM_COUNT}, generateCardFilm);
тут я бы посоветовала переименовать в filmCards

2021-12-03 06:42 UTC, ElseeCCD commented on src/mock/film-card.js
> +const descriptions = [
тут перед всеми const нужно добавить пробелы )

2021-12-03 06:42 UTC, ElseeCCD commented on src/mock/film-card.js
> +const peoples = [
people - уже множественное число, s на конце убираем )

2021-12-03 06:42 UTC, ElseeCCD commented on src/mock/film-card.js
> +    id: 1,
id должны быть уникальными ) Можешь, например, предавать в эту функцию параметр:
```
export const generateCardFilm = (id) => (
  {
    id,
    ...
```

И использовать так:
```
const cardsFilm = Array.from({length: FILM_COUNT}, (_, i) => generateCardFilm(i+1));
```

Тогда у каждого фильма должен проставить свой id от 1 до FILM_COUNT

2021-12-03 06:42 UTC, ElseeCCD commented on src/mock/filter-films.js
> +const filterWachlist = (films) => films.filter((film) => film.userDetails.isWatchlist).length;
тут опечатка Watchlist

2021-12-03 06:42 UTC, ElseeCCD commented on src/mock/filter-films.js
> +    wachlist: filterWachlist(films),
и тут Watchlist )

2021-12-03 06:42 UTC, ElseeCCD commented on src/utils.js
> +  return array;
ну тут на самом деле array возвращать не обязательно: функция мутирует то, что ей передают параметром...

2021-12-03 06:42 UTC, ElseeCCD commented on src/view/film-card-view.js
> +const duration = require('dayjs/plugin/duration');
`import duration from 'dayjs/plugin/duration';` должно работать )

2021-12-03 06:42 UTC, ElseeCCD commented on src/view/film-card-view.js
> +  const minutes =dayjs.duration(filmInfo.runTime, 'minutes').minutes(filmInfo.runTime);
после `=` не забываем пробелы )

2021-12-03 06:42 UTC, ElseeCCD commented on src/view/profile-view.js
> +  } else if (history <= 20 && history > 10) {
давай сначала напишем нижнюю границу, потом верхнюю: `history > 10 && history <= 20`. Так будет проще читать )

2021-12-03 06:42 UTC, ElseeCCD commented on src/view/profile-view.js
> +  if (history <= 10) {
тут нужен `else if`. Смотри, если history = 0,  у тебя первый if проходит, присваивает profileName = '';. Код идёт дальше, видит `if (0 <= 10) ` - это верное условие, мы зайдём в тело и выполним `profileName = 'Novice';`. Т.е. первый if получается как бы бесполезным

2021-12-05 21:09 UTC, MitKat commented on src/main.js
> +const filmCards = Array.from({length: FILM_COUNT}, (_, i) => generateCardFilm(i+1));
Привет. Я не совсем разобралась пока, что означает это нижнее подчеркивание?
Но на его основе я еще также id у комментариев сделала.

2021-12-05 21:14 UTC, MitKat commented on src/mock/film-card.js
> +    comments: generateCommentsList(),
С комментариями я поступила следующим образом, генерируя карточку фильма, я в нем создаю случайное количество комментариев, а id комментариев у меня создано по порядку.

2021-12-05 21:16 UTC, MitKat commented on src/view/comments-view.js
> +  return `<section class="film-details__comments-wrap">
Вопрос про выделение компоненты, я выбрала с тега section, и его вставляла в нужный div. Может надо было весь div вырезать?

2021-12-05 21:18 UTC, MitKat commented on src/utils.js
> +  return array;
Попробовала удалить этот return и у меня всё сломалось. На тот массив, в который я все сохраняю ругается и говорит, что это число. Больше я эту функцию не трогала.

2021-12-06 06:25 UTC, ElseeCCD commented on src/main.js
> +const filmCards = Array.from({length: FILM_COUNT}, (_, i) => generateCardFilm(i+1));
Привет! Нижнее подчеркивание это просто вместо названия аргумента, т.к. использовать мы его не будем ) Т.е. вот эта функция-маппер как работает: принимает на вход сначала сам элемент массива (вот он нам не нужен), потом его порядковый номер (а вот он нам нужен), потом еще можно массив, по которому проходимся, передать. Вот из документации, чтобы проще понимать было: "Проще говоря, вызов Array.from(obj, mapFn, thisArg) эквивалентен цепочке Array.from(obj).map(mapFn, thisArg), за исключением того, что он не создаёт промежуточного массива."

2021-12-06 06:25 UTC, ElseeCCD commented on src/utils.js
> +  return array;
А, всё, вижу, что ты сразу копию массива передаешь аргументами. А давай лучше клонирование исходного массива занесём внутрь функции, так же удобнее будет:
```
 export function shuffle(array) {
   const arrayCopy = array.slice();
   ...
   return arrayCopy;
 }
 ```

2021-12-06 06:25 UTC, ElseeCCD commented on src/view/comments-view.js
> +  return `<section class="film-details__comments-wrap">
Да вроде бы всё ок )

2021-12-06 06:25 UTC, ElseeCCD commented on src/mock/film-card.js
> +    comments: generateCommentsList(),
Т.е., получается, пока все комментарии хранишь в структуре фильма?

2021-12-06 07:01 UTC, MitKat commented on src/mock/film-card.js
> +    comments: generateCommentsList(),
Те которые уже на сервере, мы формируем в самой карточке фильме, а которые будем добавлять с помощью формы не знаю пока, где они будут.
Или нам с сервера не придут комментарии? придут только их id?

2021-12-06 07:10 UTC, ElseeCCD commented on src/mock/film-card.js
> +    comments: generateCommentsList(),
ну смотри: в структуре фильма будут храниться только id комментариев. Для каждого фильма ты с сервера будешь запрашивать свой список комментариев и по id их потом матчить. Если пока не понятно и сложно, оставь так.

2021-12-06 07:56 UTC, MitKat commented on src/mock/film-card.js
> +    comments: generateCommentsList(),
Да, давай лучше оставим пока так....я вроде понимаю, но пока сложно реализовать)

2021-12-06 08:29 UTC, ElseeCCD approved these changes

2021-12-06 08:29 UTC, ElseeCCD commented on src/view/popup-view.js
> +  const timeDuration = (hours===0) ?  `${minutes}m` : `${hours}h ${minutes}m`;
(hours===0) - вот тут круглые скобки убрать, до и после === поставить пробелы )

2021-12-06 08:31 UTC, merged