popup show and close
htmlacademy-ecmascript/199591-cinemaddict-16 pull request #6
Opened 2021-12-10 19:50 UTC by MitKat

2021-12-10 19:53 UTC, MitKat commented on src/main.js
> +    // popupComments.appendChild(new NewCommentView().element);
В задании у нас говорится использовать appendChild и removeChild. 
я сначала реализовала через функцию render, и потом возник вопрос.
По какому принципу выбирать здесь ту или иную реализацию?

2021-12-10 19:55 UTC, MitKat commented on src/main.js
> +    body.classList.add('hide-overflow');
class = hide-overflow, закрывает двойной скролл, но почему то я все равно могу кликать мышкой по кусочку карточки, и она будет открываться. Не смогла от этого избавиться.

2021-12-10 20:03 UTC, MitKat commented on src/view/films-list-view.js
> +    <div class="films-list__container">
Пока не стала добавлять сюда обертку сверху <section class="films">, так как компонент films-list вроде используется еще раз ниже.
Вот этот блок <section class="films-list films-list--extra"> я правильно понимаю, что он добавляется с помощью блока  films-list и потом модифицируется? Или мы под него должны создать свою компоненту?

2021-12-12 16:25 UTC, ElseeCCD commented on src/main.js
> +    body.classList.add('hide-overflow');
Всё правильно работает. `hide-overflow` убирает скролл, но больше-то ничего не делает со страницей, у пользователей остаётся возможность нажать на оставшиеся в поле зрения карточки. Но тут нужно обратить внимание на требование ТЗ "Одновременно может быть открыт только один попап. При открытии нового попапа прежний закрывается, например при клике на другую карточку при открытом попапе. Несохранённые изменения (неотправленный комментарий) пропадают.". Думаю, тут и ответ на твой предыдущий вопрос с выбором реализции: через `appendChild` и `removeChild` реализовать это будет проще

2021-12-12 16:26 UTC, ElseeCCD commented on src/main.js
> +    // popupComments.appendChild(new NewCommentView().element);
ну тут обрати внимание, что это комментарий к блоку попапа именно, а не к вьюхам внутри него )

2021-12-12 16:27 UTC, ElseeCCD commented on src/view/films-list-view.js
> +    <div class="films-list__container">
Тут не поняла вопрос, давай ты мне напишешь детальнее в Телеграмм и мы подробно обсудим )

2021-12-12 16:42 UTC, ElseeCCD requested changes

2021-12-12 16:42 UTC, ElseeCCD commented on src/main.js
> +  const popupShowHandler = filmCard.element.querySelector('.film-card__link');
Через `handler` обычно называем функции-обработчики, а тут у тебя ссылка на DOM-элемент. Было бы логичнее выбрать тут какое-нибудь название, которое лучше отражает суть. `filmCardTitle`, например

2021-12-12 16:42 UTC, ElseeCCD commented on src/main.js
> +  for (let i=0; i< FILM_COUNT_STEP; i++) {
давай тут пробелы расставим. `i = 0`, `i < FILM_COUNT_STEP`

2021-12-13 11:01 UTC, MitKat commented on src/main.js
> +    // popupComments.appendChild(new NewCommentView().element);
Здесь не до конца поняла. У меня в попапе есть div с комментариями, в этот div я их и добавляю.

2021-12-13 11:37 UTC, ElseeCCD commented on src/main.js
> +    // popupComments.appendChild(new NewCommentView().element);
Да, с комментариями всё хорошо. Просто ты спрашивала про то, что в задании написано использовать appendChild и removeChild. Я ответила, что это требование относится ко всем попапу. Т.е. сам попап вам советуют реализовать через appendChild и removeChild, а не блоки комментариев и т.п. внутри попапа

2021-12-13 11:39 UTC, ElseeCCD commented on src/main.js
> +    // popupComments.appendChild(new NewCommentView().element);
т.е. комментарии лучше отрисовывать через render )

2021-12-13 11:47 UTC, ElseeCCD approved these changes

2021-12-13 11:47 UTC, ElseeCCD commented on src/main.js
> +    const popupOpen = siteFooterElement.querySelector('.film-details');
тут тоже лучше над названием еще немного подумать. По ходу чтения кода может показаться, что тут должен быть булев флаг, а тут опять ссылка на DOM-элемент. `popupElement`, например, или просто `popup`

2021-12-13 11:50 UTC, merged